# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3ebc82c9875dbec253c3b0fc4b07263b1078291e79d1b59d5a4ef6183cd4e8ceb3209dc035fb4cc45184c3df6ecebd6de34d428e0c833b69286b2d3160688ef1

test:
  secret_key_base: 0170710ac975b8dbc0b15b2e8cf969af2ab0f4a40548de845ef4771a2102ff946aaf9f1fa415d883352b68db17361097a77af3c361d9bf77579fb727cfaa59a1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
